title: Spidermake Agenzia Web Udine
email: info@spidermake.com
tel: +39-388-9005888
description:
  Spiedermake Web Agency realizza Siti Internet a Udine. Crea siti web a Trieste. Posizionamento su motori di ricerca, SEO. Servizi web in Friuli.
baseurl: "/"
url: "https://www.spidermake.com"
facebook_username: spidermake
linkedin_username: spidermake

# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Spidermake | web designer Udine
  email: "info@spidermake.com"
  facebook: spidermake

#disqus: ""
disqus: "spidermake"

# Build settings
markdown: kramdown

permalink: /:month-:day-:year/:title.html
